version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:      

artifacts:
  files:
    - build*/**
  discard-paths: yes
